### PR TITLE
Update docs since `akkaSystem.shutdown()` is deprecated since 2.4

### PR DESCRIPTION
**Pull request by Ma27**
see http://doc.akka.io/docs/akka/2.4/project/migration-guide-2.3.x-2.4.x.html
for further reference

### CODE REVIEW

**Comment by juanmirocks** [comment]
This depends on #191

**Comment by Ma27** [comment]
agreed. Is there any reason why we can't merge #191 ?

**Comment by juanmirocks** [comment]
I don’t think so. It depends on @etaty.

**Comment by 2efPer** [comment]
Why didn't merge this PR?

**Comment by juanmirocks** [comment]
@2efPer pretty much the lib, although great, seems abandoned :/

**Pull request closed without merging**
