### PR TITLE
Dependencies.akkaVersion: 2.4.12 -> 2.5.6

### PR DESCRIPTION
**Pull request by Ma27**
Akka 2.4 causes a version conflict in one of my projects, so I pushed it to Akka 2.5.x

### CODE REVIEW

**Comment by Ma27** [comment]
@etaty would be cool if this could be merged :-)

**Comment by herzrasen** [comment]
+1

**Comment by kardapoltsev** [comment]
Any updates?

**Comment by Ma27** [comment]
@kardapoltsev no, currently waiting for @etaty to get some maintainer's feedback.

**Comment by sunghyunzz** [comment]
As [Akka 2.4.x is deprecated](https://akka.io/blog/news/2018/01/11/akka-2.5.9-released-2.4.x-end-of-life), this should be merged.

**Comment by Ma27** [comment]
@etaty I absolutely understand it if you don't have enough time to maintian this project anymore. However it seems as there are still people interested in this library. Therefore, would it be possible to give some folks push access so we can continue keeping this library alive?

If this won't be possible I'd suggest that someone of us (I could do this as well, however my OSS time is a bit limited unfortunately) creates a fork to keep this library at least maintained.

**Comment by herzrasen** [comment]
@Ma27 I would offer to help maintaining a fork because we'd like to use rediscala at our current project but it is not possible with the minimal maintenance it receives at the moment.

**Comment by jona7o** [comment]
we'll need this repo too, so i downloaded @Ma27 latest commit. i will publish it on maven and github tomorrow as a first new commit.

After that i'll merge the other pull requests to the new repository.

**Comment by kardapoltsev** [comment]
I think I will find some time for maintenance too. I'm interesting in this project.

**Comment by Reeebuuk** [comment]
We would also need this

**Comment by Ma27** [comment]
ok, I just invited @herzrasen, @kardapoltsev and @Reeebuuk to my personal fork. As I'll have to take care of some private things right now, I'll push the changes of my PRs tomorrow and try to setup a build/publishing pipeline so we can easily work on this.

**Comment by Reeebuuk** [comment]
I ended up using "net.debasishg"  %% "redisclient"  % "3.4"
Which is working for me as expected. IE I have a simple cache/session use case.

**Comment by Ma27** [comment]
FYI I prepared my fork and configured travis, coveralls accordingly, furthermore the fork as available on Maven central: http://search.maven.org/#artifactdetails%7Ccom.github.Ma27%7Crediscala_2.11%7C1.8.1%7Cjar

Sorry for the slight delay, I'm currently busy with a lot of private things and will be blocked by some exams in the next months, so I can only merge things and create releases, no active development.

**Comment by KarelCemus** [comment]
@Ma27 Great job, very appreciate it! Maybe you could grant push access also to some other maintainers to ensure the fork will be alive?

@etaty Thanks for this amazing library, could you find some time and grant push access to some other maintainers to ensure the continuation of your great work, please? The community would greatly appreciate it.

**Comment by Ma27** [comment]
@KarelCemus in fact I did, currently @herzrasen, @kardapoltsev and @aoldemeier have push access. In case you’re interested, I can send you an invite as well :)

**Pull request closed without merging**
