### PR TITLE
added geoadd and georadius features

### PR DESCRIPTION
**Pull request by arpitsr**
I have added beta features of geoadd and georadius available with redis 3.2

### CODE REVIEW

**Comment by etaty** [comment]
Hi, could you write some tests?

**Comment by 123avi** [comment]
Hi guys, thanks for the great project .
@etaty when this PR will be merged and closed ?
@arpitsr do you plan to add other GEO methods (e.g :
[GEODIST](https://redis.io/commands/geodist),
[GEOHASH](https://redis.io/commands/geohash),
[GEOPOS](https://redis.io/commands/geopos),
[GEORADIUSBYMEMBER](https://redis.io/commands/georadiusbymember)) ? if not pls LMK and I will add them .

**Comment by etaty** [comment]
@123avi I can't merge it without tests ;)
feel free to open a new PR (with test) and I will merge and publish a new release

**Comment by 123avi** [comment]
@etaty  , OK, I will add that functionality,  which branch should I base from ? tests are not running properly. some are falling due to `java.io.IOException: Cannot run program "/usr/local/bin/redis-trib.rb": error=2, No such file or directory` some for other exceptions (using master branch, also I have redis server running on docker ) . please advise

**Comment by etaty** [comment]
Merged GEO with PR #164

**Pull request closed without merging**
